"""Fixed acceptance tests for temperature conversion. Do not edit this file.

The harness must make temperature.py pass these tests.
"""

import unittest

from temperature import c_to_f, f_to_c


class TemperatureTests(unittest.TestCase):
    def test_freezing_c_to_f(self):
        self.assertAlmostEqual(c_to_f(0), 32.0)

    def test_boiling_c_to_f(self):
        self.assertAlmostEqual(c_to_f(100), 212.0)

    def test_body_c_to_f(self):
        self.assertAlmostEqual(c_to_f(37), 98.6)

    def test_freezing_f_to_c(self):
        self.assertAlmostEqual(f_to_c(32), 0.0)

    def test_boiling_f_to_c(self):
        self.assertAlmostEqual(f_to_c(212), 100.0)

    def test_round_trip(self):
        self.assertAlmostEqual(f_to_c(c_to_f(21)), 21.0)


if __name__ == "__main__":
    unittest.main()
